fix issue #3 - replace th_error call with new local runner_error function

diff --git a/standalone/test_runner b/standalone/test_runner
--- a/standalone/test_runner
+++ b/standalone/test_runner
@@ -27,6 +27,7 @@ RUNNER_SHELLS='/bin/sh ash /bin/bash /bin/dash /bin/ksh /bin/pdksh /bin/zsh'
 RUNNER_TEST_SUFFIX='_test.sh'
 
 runner_warn() { echo "runner:WARN $*" >&2; }
+runner_error() { echo "runner:ERROR $*" >&2; }
 runner_fatal() { echo "runner:FATAL $*" >&2; exit 1; }
 
 runner_usage() {
@@ -87,7 +88,7 @@ main() {
 
   # Error checking.
   if [ -z "${tests}" ]; then
-    th_error 'no tests found to run; exiting'
+    runner_error 'no tests found to run; exiting'
     exit 1
   fi
 
