Updated to latest shUnit2.

diff --git a/lib/shunit2 b/lib/shunit2
--- a/lib/shunit2
+++ b/lib/shunit2
@@ -1,46 +1,51 @@
 #! /bin/sh
-# $Id$
 # vim:et:ft=sh:sts=2:sw=2
 #
 # Copyright 2008 Kate Ward. All Rights Reserved.
-# Released under the LGPL (GNU Lesser General Public License)
+# Released under the Apache 2.0 license.
 #
 # shUnit2 -- Unit testing framework for Unix shell scripts.
-# http://code.google.com/p/shunit2/
+# https://github.com/kward/shunit2
 #
 # Author: kate.ward@forestent.com (Kate Ward)
 #
 # shUnit2 is a xUnit based unit test framework for Bourne shell scripts. It is
 # based on the popular JUnit unit testing framework for Java.
 
-# return if shunit already loaded
+# Return if shunit2 already loaded.
 [ -n "${SHUNIT_VERSION:-}" ] && exit 0
 SHUNIT_VERSION='2.1.7pre'
 
-# return values that scripts can use
+# Return values that scripts can use.
 SHUNIT_TRUE=0
 SHUNIT_FALSE=1
 SHUNIT_ERROR=2
 
-# logging functions
+# Logging functions.
 _shunit_warn() { echo "shunit2:WARN $@" >&2; }
 _shunit_error() { echo "shunit2:ERROR $@" >&2; }
 _shunit_fatal() { echo "shunit2:FATAL $@" >&2; exit ${SHUNIT_ERROR}; }
 
-# determine some reasonable command defaults
+# Determine some reasonable command defaults.
 __SHUNIT_UNAME_S=`uname -s`
 case "${__SHUNIT_UNAME_S}" in
-  BSD) __SHUNIT_EXPR_CMD='gexpr' ;;
-  *) __SHUNIT_EXPR_CMD='expr' ;;
+  BSD) __SHUNIT_CMD_EXPR='gexpr' ;;
+  *) __SHUNIT_CMD_EXPR='expr' ;;
 esac
 
-# commands a user can override if needed
-SHUNIT_EXPR_CMD=${SHUNIT_EXPR_CMD:-${__SHUNIT_EXPR_CMD}}
+__SHUNIT_CMD_ECHO_ESC='echo -e'
+[ "`echo -e test`" = '-e test' ] && __SHUNIT_CMD_ECHO_ESC='echo'
 
-# enable strict mode by default
+# Commands a user can override if needed.
+SHUNIT_CMD_EXPR=${SHUNIT_CMD_EXPR:-${__SHUNIT_CMD_EXPR}}
+
+# Enable strict mode by default.
 SHUNIT_STRICT=${SHUNIT_STRICT:-${SHUNIT_TRUE}}
 
-# specific shell checks
+# Enable color output. Options are 'never', 'always', or 'auto'.
+SHUNIT_COLOR=${SHUNIT_COLOR:-auto}
+
+# Specific shell checks.
 if [ -n "${ZSH_VERSION:-}" ]; then
   setopt |grep "^shwordsplit$" >/dev/null
   if [ $? -ne ${SHUNIT_TRUE} ]; then
@@ -53,15 +58,20 @@ if [ -n "${ZSH_VERSION:-}" ]; then
 fi
 
 #
-# constants
+# Constants
 #
 
-__SHUNIT_ASSERT_MSG_PREFIX='ASSERT:'
 __SHUNIT_MODE_SOURCED='sourced'
 __SHUNIT_MODE_STANDALONE='standalone'
 __SHUNIT_PARENT=${SHUNIT_PARENT:-$0}
 
-# set the constants readonly
+# ANSI colors.
+__SHUNIT_ANSI_NONE='\033[0m'
+__SHUNIT_ANSI_RED='\033[1;31m'
+__SHUNIT_ANSI_GREEN='\033[1;32m'
+__SHUNIT_ANSI_CYAN='\033[1;36m'
+
+# Set the constants readonly.
 __shunit_constants=`set |grep '^__SHUNIT_' |cut -d= -f1`
 echo "${__shunit_constants}" |grep '^Binary file' >/dev/null && \
     __shunit_constants=`set |grep -a '^__SHUNIT_' |cut -d= -f1`
@@ -71,44 +81,50 @@ for __shunit_const in ${__shunit_constants}; do
   else
     case ${ZSH_VERSION} in
       [123].*) readonly ${__shunit_const} ;;
-      *) readonly -g ${__shunit_const}  # declare readonly constants globally
+      *) readonly -g ${__shunit_const}  # Declare readonly constants globally.
     esac
   fi
 done
 unset __shunit_const __shunit_constants
 
 #
-# internal variables
+# Internal variables.
 #
 
-# variables
-__shunit_lineno=''  # line number of executed test
-__shunit_mode=${__SHUNIT_MODE_SOURCED}  # operating mode
-__shunit_reportGenerated=${SHUNIT_FALSE}  # is report generated
-__shunit_script=''  # filename of unittest script (standalone mode)
-__shunit_skip=${SHUNIT_FALSE}  # is skipping enabled
-__shunit_suite=''  # suite of tests to execute
+# Variables.
+__shunit_lineno=''  # Line number of executed test.
+__shunit_mode=${__SHUNIT_MODE_SOURCED}  # Operating mode.
+__shunit_reportGenerated=${SHUNIT_FALSE}  # Is report generated.
+__shunit_script=''  # Filename of unittest script (standalone mode).
+__shunit_skip=${SHUNIT_FALSE}  # Is skipping enabled.
+__shunit_suite=''  # Suite of tests to execute.
 
-# counts of tests
+# ANSI colors (populated by _shunit_configureColor()).
+__shunit_ansi_none=''
+__shunit_ansi_red=''
+__shunit_ansi_green=''
+__shunit_ansi_cyan=''
+
+# Counts of tests.
 __shunit_testSuccess=${SHUNIT_TRUE}
 __shunit_testsTotal=0
 __shunit_testsPassed=0
 __shunit_testsFailed=0
 
-# counts of asserts
+# Counts of asserts.
 __shunit_assertsTotal=0
 __shunit_assertsPassed=0
 __shunit_assertsFailed=0
 __shunit_assertsSkipped=0
 
-# macros
+#
+# Macros
+#
+
 _SHUNIT_LINENO_='eval __shunit_lineno=""; if [ "${1:-}" = "--lineno" ]; then [ -n "$2" ] && __shunit_lineno="[$2] "; shift 2; fi'
 
 #-----------------------------------------------------------------------------
-# private functions
-
-#-----------------------------------------------------------------------------
-# assert functions
+# Assertion functions.
 #
 
 # Assert that two values are equal to one another.
@@ -345,23 +361,23 @@ assertTrue()
   fi
   shunit_condition_=$1
 
-  # see if condition is an integer, i.e. a return value
+  # See if condition is an integer, i.e. a return value.
   shunit_match_=`expr "${shunit_condition_}" : '\([0-9]*\)'`
   shunit_return=${SHUNIT_TRUE}
   if [ -z "${shunit_condition_}" ]; then
-    # null condition
+    # Null condition.
     shunit_return=${SHUNIT_FALSE}
   elif [ -n "${shunit_match_}" -a "${shunit_condition_}" = "${shunit_match_}" ]
   then
-    # possible return value. treating 0 as true, and non-zero as false.
+    # Possible return value. Treating 0 as true, and non-zero as false.
     [ ${shunit_condition_} -ne 0 ] && shunit_return=${SHUNIT_FALSE}
   else
-    # (hopefully) a condition
+    # Hopefully... a condition.
     ( eval ${shunit_condition_} ) >/dev/null 2>&1
     [ $? -ne 0 ] && shunit_return=${SHUNIT_FALSE}
   fi
 
-  # record the test
+  # Record the test.
   if [ ${shunit_return} -eq ${SHUNIT_TRUE} ]; then
     _shunit_assertPass
   else
@@ -410,23 +426,23 @@ assertFalse()
   fi
   shunit_condition_=$1
 
-  # see if condition is an integer, i.e. a return value
+  # See if condition is an integer, i.e. a return value.
   shunit_match_=`expr "${shunit_condition_}" : '\([0-9]*\)'`
   shunit_return=${SHUNIT_TRUE}
   if [ -z "${shunit_condition_}" ]; then
-    # null condition
+    # Null condition.
     shunit_return=${SHUNIT_FALSE}
   elif [ -n "${shunit_match_}" -a "${shunit_condition_}" = "${shunit_match_}" ]
   then
-    # possible return value. treating 0 as true, and non-zero as false.
+    # Possible return value. Treating 0 as true, and non-zero as false.
     [ ${shunit_condition_} -eq 0 ] && shunit_return=${SHUNIT_FALSE}
   else
-    # (hopefully) a condition
+    # Hopefully... a condition.
     ( eval ${shunit_condition_} ) >/dev/null 2>&1
     [ $? -eq 0 ] && shunit_return=${SHUNIT_FALSE}
   fi
 
-  # record the test
+  # Record the test.
   if [ ${shunit_return} -eq ${SHUNIT_TRUE} ]; then
     _shunit_assertPass
   else
@@ -439,7 +455,7 @@ assertFalse()
 _ASSERT_FALSE_='eval assertFalse --lineno "${LINENO:-}"'
 
 #-----------------------------------------------------------------------------
-# failure functions
+# Failure functions.
 #
 
 # Records a test failure.
@@ -565,7 +581,7 @@ failNotSame()
 _FAIL_NOT_SAME_='eval failNotSame --lineno "${LINENO:-}"'
 
 #-----------------------------------------------------------------------------
-# skipping functions
+# Skipping functions.
 #
 
 # Force remaining assert and fail functions to be "skipped".
@@ -602,7 +618,7 @@ isSkipping()
 }
 
 #-----------------------------------------------------------------------------
-# suite functions
+# Suite functions.
 #
 
 # Stub. This function should contains all unit test calls to be made.
@@ -672,7 +688,7 @@ suite_addTest()
 #
 # Args:
 #   None
-#setUp() { :; }
+#setUp() { :; }  # DO NOT UNCOMMENT THIS FUNCTION
 
 # Note: see _shunit_mktempFunc() for actual implementation
 # Stub. This function will be called after each test is run.
@@ -687,13 +703,13 @@ suite_addTest()
 #tearDown() { :; }  # DO NOT UNCOMMENT THIS FUNCTION
 
 #------------------------------------------------------------------------------
-# internal shUnit2 functions
+# Internal shUnit2 functions.
 #
 
 # Create a temporary directory to store various run-time files in.
 #
 # This function is a cross-platform temporary directory creation tool. Not all
-# OSes have the mktemp function, so one is included here.
+# OSes have the `mktemp` function, so one is included here.
 #
 # Args:
 #   None
@@ -701,18 +717,18 @@ suite_addTest()
 #   string: the temporary directory that was created
 _shunit_mktempDir()
 {
-  # try the standard mktemp function
+  # Try the standard `mktemp` function.
   ( exec mktemp -dqt shunit.XXXXXX 2>/dev/null ) && return
 
-  # the standard mktemp didn't work.  doing our own.
+  # The standard `mktemp` didn't work. Use our own.
   if [ -r '/dev/urandom' -a -x '/usr/bin/od' ]; then
     _shunit_random_=`/usr/bin/od -vAn -N4 -tx4 </dev/urandom \
         |sed 's/^[^0-9a-f]*//'`
   elif [ -n "${RANDOM:-}" ]; then
-    # $RANDOM works
+    # `$RANDOM` works.
     _shunit_random_=${RANDOM}${RANDOM}${RANDOM}$$
   else
-    # $RANDOM doesn't work
+    # `$RANDOM` doesn't work.
     _shunit_date_=`date '+%Y%m%d%H%M%S'`
     _shunit_random_=`expr ${_shunit_date_} / $$`
   fi
@@ -766,15 +782,15 @@ _shunit_cleanup()
       ;;
   esac
 
-  # do our work
+  # Do our work.
   rm -fr "${__shunit_tmpDir}"
 
-  # exit for all non-EXIT signals
+  # Exit for all non-EXIT signals.
   if [ ${_shunit_name_} != 'EXIT' ]; then
     _shunit_warn "trapped and now handling the (${_shunit_name_}) signal"
-    # disable EXIT trap
+    # Disable EXIT trap.
     trap 0
-    # add 128 to signal and exit
+    # Add 128 to signal and exit.
     exit `expr ${_shunit_signal_} + 128`
   elif [ ${__shunit_reportGenerated} -eq ${SHUNIT_FALSE} ] ; then
     _shunit_assertFail 'Unknown failure encountered running a test'
@@ -783,6 +799,43 @@ _shunit_cleanup()
   fi
 
   unset _shunit_name_ _shunit_signal_
+}
+
+# configureOutput based on user preferences, e.g. color.
+#
+# Args:
+#   color: string: color mode (one of `always`, `auto`, or `none`).
+_shunit_configureColor() {
+  _shunit_color_=${SHUNIT_FALSE}  # By default, no color.
+  case $1 in
+    'always') _shunit_color_=${SHUNIT_TRUE} ;;
+    'auto')
+      ( exec tput >/dev/null 2>&1 )  # Check for existence of tput command.
+      if [ $? -lt 127 ]; then
+        _shunit_tput_=`tput colors`
+        [ $? -eq 0 -a ${_shunit_tput_} -ge 16 ] && _shunit_color_=${SHUNIT_TRUE}
+      fi
+      ;;
+    'none') ;;
+    *) _shunit_fatal "unrecognized SHUNIT_COLOR option '${SHUNIT_COLOR}'" ;;
+  esac
+
+  case ${_shunit_color_} in
+    ${SHUNIT_TRUE})
+      __shunit_ansi_none=${__SHUNIT_ANSI_NONE}
+      __shunit_ansi_red=${__SHUNIT_ANSI_RED}
+      __shunit_ansi_green=${__SHUNIT_ANSI_GREEN}
+      __shunit_ansi_cyan=${__SHUNIT_ANSI_CYAN}
+      ;;
+    ${SHUNIT_FALSE})
+      __shunit_ansi_none=''
+      __shunit_ansi_red=''
+      __shunit_ansi_green=''
+      __shunit_ansi_cyan=''
+      ;;
+  esac
+
+  unset _shunit_color_ _shunit_tput_
 }
 
 # The actual running of the tests happens here.
@@ -828,16 +881,16 @@ _shunit_generateReport()
 {
   _shunit_ok_=${SHUNIT_TRUE}
 
-  # if no exit code was provided one, determine an appropriate one
+  # If no exit code was provided one, determine an appropriate one.
   [ ${__shunit_testsFailed} -gt 0 \
       -o ${__shunit_testSuccess} -eq ${SHUNIT_FALSE} ] \
           && _shunit_ok_=${SHUNIT_FALSE}
 
   echo
   if [ ${__shunit_testsTotal} -eq 1 ]; then
-    echo "Ran ${__shunit_testsTotal} test."
+    ${__SHUNIT_CMD_ECHO_ESC} "Ran ${__shunit_ansi_cyan}${__shunit_testsTotal}${__shunit_ansi_none} test."
   else
-    echo "Ran ${__shunit_testsTotal} tests."
+    ${__SHUNIT_CMD_ECHO_ESC} "Ran ${__shunit_ansi_cyan}${__shunit_testsTotal}${__shunit_ansi_none} tests."
   fi
 
   _shunit_failures_=''
@@ -848,18 +901,18 @@ _shunit_generateReport()
       && _shunit_skipped_="skipped=${__shunit_assertsSkipped}"
 
   if [ ${_shunit_ok_} -eq ${SHUNIT_TRUE} ]; then
-    _shunit_msg_='OK'
+    _shunit_msg_="${__shunit_ansi_green}OK"
     [ -n "${_shunit_skipped_}" ] \
         && _shunit_msg_="${_shunit_msg_} (${_shunit_skipped_})"
   else
-    _shunit_msg_="FAILED (${_shunit_failures_}"
+    _shunit_msg_="${__shunit_ansi_red}FAILED (${_shunit_failures_}"
     [ -n "${_shunit_skipped_}" ] \
         && _shunit_msg_="${_shunit_msg_},${_shunit_skipped_}"
     _shunit_msg_="${_shunit_msg_})"
   fi
 
   echo
-  echo ${_shunit_msg_}
+  ${__SHUNIT_CMD_ECHO_ESC} "${_shunit_msg_}${__shunit_ansi_none}"
   __shunit_reportGenerated=${SHUNIT_TRUE}
 
   unset _shunit_failures_ _shunit_msg_ _shunit_ok_ _shunit_skipped_
@@ -898,7 +951,8 @@ _shunit_assertFail()
   __shunit_testSuccess=${SHUNIT_FALSE}
   __shunit_assertsFailed=`expr ${__shunit_assertsFailed} + 1`
   __shunit_assertsTotal=`expr ${__shunit_assertsTotal} + 1`
-  echo "${__SHUNIT_ASSERT_MSG_PREFIX}${_shunit_msg_}"
+  ${__SHUNIT_CMD_ECHO_ESC} \
+      "${__shunit_ansi_red}ASSERT:${__shunit_ansi_none}${_shunit_msg_}"
 
   unset _shunit_msg_
 }
@@ -984,7 +1038,7 @@ _shunit_extractTestFunctions()
 {
   _shunit_script_=$1
 
-  # extract the lines with test function names, strip of anything besides the
+  # Extract the lines with test function names, strip of anything besides the
   # function name, and output everything on a single line.
   _shunit_regex_='^[ 	]*(function )*test[A-Za-z0-9_]* *\(\)'
   egrep "${_shunit_regex_}" "${_shunit_script_}" \
@@ -995,10 +1049,10 @@ _shunit_extractTestFunctions()
 }
 
 #------------------------------------------------------------------------------
-# main
+# Main.
 #
 
-# determine the operating mode
+# Determine the operating mode.
 if [ $# -eq 0 ]; then
   __shunit_script=${__SHUNIT_PARENT}
   __shunit_mode=${__SHUNIT_MODE_SOURCED}
@@ -1009,42 +1063,45 @@ else
   __shunit_mode=${__SHUNIT_MODE_STANDALONE}
 fi
 
-# create a temporary storage location
+# Create a temporary storage location.
 __shunit_tmpDir=`_shunit_mktempDir`
 
-# provide a public temporary directory for unit test scripts
-# TODO(kward): document this
+# Provide a public temporary directory for unit test scripts.
+# TODO(kward): document this.
 SHUNIT_TMPDIR="${__shunit_tmpDir}/tmp"
 mkdir "${SHUNIT_TMPDIR}"
 
-# setup traps to clean up after ourselves
+# Setup traps to clean up after ourselves.
 trap '_shunit_cleanup EXIT' 0
 trap '_shunit_cleanup INT' 2
 trap '_shunit_cleanup TERM' 15
 
-# create phantom functions to work around issues with Cygwin
+# Create phantom functions to work around issues with Cygwin.
 _shunit_mktempFunc
 PATH="${__shunit_tmpDir}:${PATH}"
 
-# make sure phantom functions are executable. this will bite if /tmp (or the
-# current $TMPDIR) points to a path on a partition that was mounted with the
-# 'noexec' option. the noexec command was created with _shunit_mktempFunc().
+# Make sure phantom functions are executable. This will bite if `/tmp` (or the
+# current `$TMPDIR`) points to a path on a partition that was mounted with the
+# 'noexec' option. The noexec command was created with `_shunit_mktempFunc()`.
 noexec 2>/dev/null || _shunit_fatal \
-    'please declare TMPDIR with path on partition with exec permission'
+    'Please declare TMPDIR with path on partition with exec permission.'
 
-# we must manually source the tests in standalone mode
+# We must manually source the tests in standalone mode.
 if [ "${__shunit_mode}" = "${__SHUNIT_MODE_STANDALONE}" ]; then
   . "`_shunit_prepForSourcing \"${__shunit_script}\"`"
 fi
 
-# execute the oneTimeSetUp function (if it exists)
+# Configure default output coloring behavior.
+_shunit_configureColor ${SHUNIT_COLOR}
+
+# Execute the oneTimeSetUp function (if it exists).
 oneTimeSetUp
 
-# execute the suite function defined in the parent test script
-# deprecated as of 2.1.0
+# Execute the suite function defined in the parent test script.
+# DEPRECATED as of 2.1.0.
 suite
 
-# if no suite function was defined, dynamically build a list of functions
+# If no suite function was defined, dynamically build a list of functions.
 if [ -z "${__shunit_suite}" ]; then
   shunit_funcs_=`_shunit_extractTestFunctions "${__shunit_script}"`
   for shunit_func_ in ${shunit_funcs_}; do
@@ -1053,15 +1110,10 @@ if [ -z "${__shunit_suite}" ]; then
 fi
 unset shunit_func_ shunit_funcs_
 
-# execute the tests
 _shunit_execSuite
-
-# execute the oneTimeTearDown function (if it exists)
 oneTimeTearDown
-
-# generate the report
 _shunit_generateReport
 
-# that's it folks
+# That's it folks.
 [ ${__shunit_testsFailed} -eq 0 ]
 exit $?
